<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sergin.SharedKernel.Domain\Sergin.SharedKernel.Domain.csproj" />
  </ItemGroup>
</Project>
